### ISSUE TITLE
Your extension is affected by event stream and have been blocked 

### ISSUE THREAD

**Issue by auchenberg** [sgwozdz/jenkinsfile-support#17]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) Fix the extension, submit an update to the marketplace
2) Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

**Comment by sgwozdz** [comment]
Hi,
Thank you for information. Necessary update is done. I'm waiting for verification.

**Comment by auchenberg** [comment]
Hi Szymon,

We have run our validation and unblocked your extension.

Sorry about the trouble.

/k

**Comment by J00MZ** [comment]
@sgwozdz 
Just encoountered a new version 0.4.2 pushed out that installed side by side with 0.4.1 that includes malicious library flatmap-stream
Detected Trojan on my PC...
![annotation 2019-02-03 104604](https://user-images.githubusercontent.com/3058176/52174768-7654d600-27a1-11e9-83bb-2b91c8e62af4.jpg)
