### ISSUE TITLE
New version with vulnerablility being pushed out as v0.4.2

### ISSUE THREAD

**Issue by J00MZ** [sgwozdz/jenkinsfile-support#21]
@sgwozdz 
Just encountered a new version 0.4.2 pushed out that installed side by side with v0.4.1 on my PC and included the malicious library flatmap-stream

See screenshot

![annotation 2019-02-03 104604](https://user-images.githubusercontent.com/3058176/52174768-7654d600-27a1-11e9-83bb-2b91c8e62af4.jpg)

_Originally posted by @J00MZ in https://github.com/sgwozdz/jenkinsfile-support/issues/17#issuecomment-460034073_

**Comment by sgwozdz** [comment]
Hi,
I'm verifying this, it was an issue some time ago. But I've done security update and MS unblocked my extension.

Currently everything seems to be fine, I scaned extension with McAfee, nothing found.

**Comment by J00MZ** [comment]
Are you familiar with a version 0.4.2 ?

**Comment by sgwozdz** [comment]
Yes, this version contained only few changed lines in snippets support. But don't worry I know already what is going on, fix will be soon.

**Comment by sgwozdz** [comment]
Looks like it done with 0.4.3 -> #22
