### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by matsumatsu233** [sgwozdz/jenkinsfile-support#27]
I didn't find any code formatter for neither groovy nor jenkinsfile on vscode extension market. It would be nice to me if this plugin can include a formatter :)

**Comment by britho** [comment]
I agree that it would be nice. I think that the current project name would be a bit misleading in that matter if it included a format tool. I don't think that users would expect it to format their files. I don't think many people read the plugin documentation, to be honest.

It might be best to add it as its own plugin.

**Comment by matsumatsu233** [comment]
Actually I thought this library were using a groovy parser to do the coloring stuff, so I thought it shouldn't be too hard to add a code formatting feature.

But after seeing [this file](https://github.com/sgwozdz/jenkinsfile-support/blob/master/syntaxes/jenkinsfile.tmLanguage.json
) it looks this library is using pattern matching rather than parsing (Please point out if I'm wrong).

In this case, I also agree with @britho that it would be better to create a own plugin. So I'll close this PR.

Feel free to reopen it if you have further concerns :)
