### ISSUE TITLE
Script could not begin with pipeline block 

### ISSUE THREAD

**Issue by leandrojdl** [sgwozdz/jenkinsfile-support#36]
Hi, I recent upgrade the plugin to v1.0.0 and now I have this lint error: "Script must not begin with pipeline block".

I think this is a mistake because I could write some code before `pipeline`, for example:

shebang groovy

```groovy
#!groovy

pipeline {}
```

library import

```groovy
@Library('myLib')

pipeline {}
```

or maybe some function

```groovy
def myFun() {
  echo 'hello there'
}

pipeline {}
```

All those things are valid syntax.

Thanks!

> Edit: I forgot to say that this lint error is not present in previous version (0.4.4)

**Comment by divinebovine** [comment]
Likewise, I'm seeing the following lint error on scripted pipelines. 
> "Script must begin with pipeline block"

e.g.

```groovy
#! /usr/bin/env groovy
NodeLabel = 'linux'

node(NodeLabel) {
  echo 'hello world'
}
```

**Comment by sgwozdz** [comment]
that's what happen when you write extension to something you're not using on daily basics 😄 
it was taken from the documentation [link](https://jenkins.io/doc/book/pipeline/syntax/#declarative-pipeline)
