### ISSUE TITLE
Nested string interpolation not highlighted correctly

### ISSUE THREAD

**Issue by Christopher-Chappell** [sgwozdz/jenkinsfile-support#37]
The following gets interpolated correctly by Jenkins but renders incorrectly in my editor.

Code:
```groovy
EXAMPLE_ENV = "${flag ? "Nested ${interpolation}" : "Default"}"

NEXT_ENV = "Something else"
```

Editor view:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/56929130/78147180-256e5b00-7401-11ea-9c5b-8f8716445e93.png">

**Comment by St4rz** [comment]
The inner quotes should be escaped.

**Comment by Christopher-Chappell** [comment]
@St4rz I'm not sure I understand what you mean.

If I were to change it to
```groovy
EXAMPLE_ENV = "${flag ? \"Nested ${interpolation}\" : \"Default\"}"

NEXT_ENV = "Something else"
```
my builds would actually fail:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 47: unexpected char: '\' @ line 47, column 33.
           EXAMPLE_ENV = "${flag ? \"Nested ${interpolation}\" : \"Default\"}"
                                   ^

1 error
```
because everything inside the curly braces is being interpreted as real Groovy code, and the strings are real Groovy strings.

**Comment by St4rz** [comment]
Oh yeah forgot that Groovy tidbit. Apologies. What a weird language. I'll look into getting your issue fixed.

**Comment by sgwozdz** [comment]
Fix pushed to master branch will go with the next version - 1.1.0.

**Comment by sgwozdz** [comment]
@Christopher-Chappell hope latest release fixed your problem

**Comment by Christopher-Chappell** [comment]
I tried it out.  I think I miss seeing the syntax highlighting inside the interpolated block, but I can understand how that might be difficult to achieve.

Here's what the same block I saw earlier looks like now:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/56929130/83898047-5f6f1c80-a724-11ea-9075-9a5c2cdd636b.png">

It kind of looks like the interpolation is just being ignored and the stuff inside the nested quotes is being treated as though it was outside the string.  At least this doesn't result in an off-by-one quoting error, though, like it was before.

**Comment by sgwozdz** [comment]
I'm intrigued... for me it looks like this 
![image](https://user-images.githubusercontent.com/5880551/83906539-0a52fb00-a764-11ea-9348-7a088500c995.png)

At least for now I don't have better solution for that. It's handled by this regex if you would like to play with it `(?<=\\{).+(?=\\})`
