### ISSUE TITLE
False positive error (multiple "parameters" statements)

### ISSUE THREAD

**Issue by superzulu** [sgwozdz/jenkinsfile-support#41]
I'm getting an error that "parameters" is only allowed once in a file ("It is not allowed to use parameters more than once).  

I think this is a false positive because I can call multiple parameterized jobs from my job.

**Comment by sgwozdz** [comment]
Hey, @superzulu could you share some code to show the example? It was taken from the documenation [link](https://jenkins.io/doc/book/pipeline/syntax/#parameters)

**Comment by milesjordan** [comment]
I'm seeing this too, when I have `parameters` as the name of a function that I'm using. The error should probably only appear when `parameters` appears more than once as a direct child of `pipeline`. This is an example of where it goes wrong for me:
```
pipeline {
  parameters {
    ...
  }
  stages{ 
    stage('My stage') {
      steps {
        myfunction(
          someargument: "somevalue"
          parameters: [
            ...
          ]
        )
      }
    }
  }
}
```

**Comment by milesjordan** [comment]
I see you've fixed it in https://github.com/sgwozdz/jenkinsfile-support/pull/45
