### ISSUE TITLE
False positive - script must begin with pipeline block

### ISSUE THREAD

**Issue by fuzzmz** [sgwozdz/jenkinsfile-support#47]
If in a pipeline you define global (groovy) variables then the script falsely reports that `Script must begin with pipeline block`.

For example, the bellow code is a valid Jenkinsfile despite the error shown by the plugin.

```groovy
def SAMPLE_VAR = ''

pipeline {
    agent { label 'master' }
    stages {
        stage('build') {
            steps {
                echo 'Sample stuff'
            }
        }
    }
}
```

**Comment by sgwozdz** [comment]
Duplicated - #36 
waits for release :)

**Comment by sgwozdz** [comment]
@fuzzmz can you confirm it works for you now ?
